### ISSUE TITLE
Minecraft Collections v1

### ISSUE THREAD

**Issue by tozydev** [GrassMC/minecraft-collections#6]
```[tasklist]
### Tasks
- [ ] https://github.com/GrassMC/minecraft-collections/issues/5
- [ ] https://github.com/GrassMC/minecraft-collections/issues/7
- [ ] https://github.com/GrassMC/minecraft-collections/issues/8
- [ ] https://github.com/GrassMC/minecraft-collections/issues/9
- [ ] https://github.com/GrassMC/minecraft-collections/issues/10
```
